apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: nodepool-medium-arm64
spec:
  disruption:
    consolidateAfter: 1m
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - arm64
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
            - spot
        - key: eks.amazonaws.com/instance-category
          operator: In
          values:
            - t
            - m
            - r
            - c
        - key: eks.amazonaws.com/instance-size
          operator: In
          values:
            - medium
