apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: goto-apps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
        # Check the URL by executing kubectl cluster-info if ArgoCD is running on a different EKS cluster.
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'goto-{{env}}-eks-project'
    spec:
      project: default
      source:
        repoURL: https://github.com/gotokazuki/todo-k8s-manifest.git
        targetRevision: main
        path: manifests/argocd/env/{{env}}
        directory:
          recurse: true
      destination:
        server: '{{url}}'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - PruneLast=true
        - ApplyOutOfSyncOnly=true
        - Validate=false
